ligurio/lua-c-api-tests

tests/luaL_buffaddr_test.c, tests/luaL_bufflen_test.c, tests/luaL_buffsub_test.c
According to Lua Reference [1] one should copy the string in already allocated space by luaL_buffinitsize
[1] https://www.lua.org/manual/5.3/manual.html#luaL_Buffer
=> Fix luaL_Buffer usage

cmake/BuildLua.cmake, cmake/BuildLuaJIT.cmake
```
cmake: enable additional Lua compile options
- LUAI_ASSERT and LUA_USE_ASSERT turns on all assertions inside Lua.
- LUA_USE_APICHECK turns on several consistency checks on the C API.
```
=> cmake: enable Lua compile options

tests/lua_load_test.c
Hi! I've found an error in fuzz target `lua_load_test`.
The `size` variable was declared in `luaZ_fill`, but not initialized. Later it is passed to `Reader` function, which is declared in fuzz target code. The `size` variable has to be filled in `Reader`.
Because `size` was not initialized, but was later used, the UB can occur later in `luaZ_fill`.
Fixed it with setting `size` to the result of `fread`.
=> Fix using of unitialized value.

tests/luaL_addgsub_test.cc, tests/luaL_buffsub_test.cc, tests/luaL_gsub_test.cc
The heap buffer overflow occurred because of `buf_size` value, which could be greater than the original string size. FDP gives the random length substring constrained by max length parameter and original string size.
Fixed with passing original string size as the max size paramter to FDP. Removed getting random `buf_size`, because FDP already returns random length string.
=> tests: fix of heap buffer overflow

tests/luaL_loadbuffer_test.c, tests/luaL_loadbufferx_test.c, tests/lua_load_test.c
This commit fixes an OOM error I was facing when using LLVM fuzzer
=> Cleanup state on exit

cmake/BuildLuaJIT.cmake
Commit 0839df9c ("cmake: enable additional Lua compile options") enables macros `LUAI_ASSERT` in LuaJIT by mistake. The same macros for LuaJIT has another name - `LUA_USE_ASSERT`. Patch fixes that.
=> cmake: fix macros that enables assertions in LuaJIT

cmake/BuildLuaJIT.cmake, patches/luajit-v2.1.patch
The patch turns off leak checks in buildvm, because it is a part of infrastructure and leaks there are not interesting, and disables Address Sanitizer for two functions: `lj_str_new` and `lj_str_cmp`, because these functions may read past a buffer end, that's ok.
With CMake option ENABLE_ASAN LuaJIT will use system malloc (`-DLUAJIT_USE_SYSMALLOC=1`), because memory allocator used by LuaJIT is not instrumented by ASAN.
Fixes #22
=> cmake: support AddressSanitizer in LuaJIT

tests/CMakeLists.txt, tests/lua_dump_test.c
> lua_dump() dumps a function as a binary chunk. Receives a Lua function
> on the top of the stack and produces a binary chunk that, if loaded
> again, results in a function equivalent to the one dumped. As it
> produces parts of the chunk, lua_dump calls function writer with the
> given data to write them [1].
Test does not execute a binary chunk because it is focused on a Lua runtime frontend. Thereby, high speed of fuzzing is achieved.
1. https://www.lua.org/manual/5.1/manual.html#3
=> tests: add lua_dump_test

CMakeLists.txt, README.md, cmake/BuildLuaJIT.cmake
The patch adds support of the option `LUAJIT_RANDOM_RA` that causes the register allocator to (often) randomly choose any register from the allowed set, rather than the default (and highly desirable) behaviour of choosing a free or cheaply evictable register, which helps to exercise rare cases and flush out bugs, see [1].
1. https://github.com/LuaJIT/LuaJIT/commit/41fb94defa8f830ce69a8122b03f6ac3216d392a
=> cmake: support LUAJIT_RANDOM_RA

tests/CMakeLists.txt, tests/lua_dump_test.c
`lua_dump()` receives a Lua function on the top of the stack and this requires running `luaL_loadstring()` or similar function. However, translation junk to bytecode is unsafe in LuaJIT.
Disable test until we have a mutations in Lua code.
=> tests: disable lua_dump_test

.github/workflows/oss-fuzz.yml, tests/lua_load_test.c
OSS Fuzz workflow has failed due to assert:
```
2023-09-26 10:00:12,722 - root - INFO - Starting fuzzing
Traceback (most recent call last):
File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 96, in <module>
sys.exit(main())
File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 92, in main
return run_fuzzers_entrypoint()
File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 62, in run_fuzzers_entrypoint
result = run_fuzzers.run_fuzzers(config)
File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 316, in run_fuzzers
if not fuzz_target_runner.run_fuzz_targets():
File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 131, in run_fuzz_targets
result = self.run_fuzz_target(target)
File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 259, in …
```
=> ci: fix broken OSS Fuzz workflow

.github/workflows/oss-fuzz.yml, cmake/BuildLua.cmake, tests/lua_load_test.c
Commit 2d803e38b6e9 ("cmake: introduce options ENABLE_LUA_ASSERT and ENABLE_LUA_APICHECK") disabled ENABLE_LUA_ASSERT for PUC Rio Lua by default due to regression introduced in [1].
Now regression has been fixed by commit [2] and ENABLE_LUA_ASSERT can be enabled back.
1. https://github.com/lua/lua/commit/9b4f39ab14fb2e55345c3d23537d129dac23b091
2. https://github.com/lua/lua/commit/07a9eab23ac073362f231ddc7215688cf221ff45
=> cmake: enable ENABLE_LUA_ASSERT

tests/luaL_loadbuffer_proto/luaL_loadbuffer_proto_test.cc
Test luaL_loadbuffer_proto generates random Lua programs and executes them. We want to build a fuzzing test that will produce Lua programs that will not contain semantic errors and will trigger as much as
possible components in LuaJIT.
Proposed patch introduces a metrics that gathered after running the test. LuaJIT metrics gathered using *unofficial* LuaJIT Lua function `jit.attach`. All gathered metrics test will output after running with a finite number of runs or finite duration of time (options `-runs` and `-max_total_time`).
```
$ ./build/tests/luaL_loadbuffer_proto/luaL_loadbuffer_proto_test -runs=1000
<snipped>
Done 1000 runs in 0 second(s)
Total number of samples: 1000
Total number of samples with errors: 738 (73%)
Total number of samples with record traces: 259 (25%)
Total number …
```
=> Collect and print LuaJIT metrics

CMakeLists.txt, cmake/BuildLua.cmake, cmake/BuildLuaJIT.cmake, cmake/CodeCoverage.cmake
The patch adds building code coverage report using gcovr [1] and llvm-cov. gcovr is a better version of lcov, see [2].
New CMake target "coverage-report" processes *.gcno and *.gcda files with llvm-cov, builds a detailed HTML report using gcovr and prints a summary. This target doesn't run any tests.
```
$ CC=clang CXX=clang++ cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_COV=ON -DUSE_LUA=ON $ RUNS=1 cmake --build build --parallel --target test $ cmake --build build --parallel --target coverage-report Building coverage report
(INFO) - MainThread - Reading coverage data...
(INFO) - MainThread - Writing coverage report...
lines: 59.4% (6974 out of 11733)
functions: 65.0% (683 out of 1050)
branches: 43.3% (4705 out of 10863)
decisions: 55.5% (1782 out of 3208)
Built target …
```
=> cmake: support building code coverage report

.gitignore, CMakePresets.json
One problem that CMake users often face is sharing settings with other
people for common ways to configure a project. CMake supports two main
files, `CMakePresets.json` and `CMakeUserPresets.json`, that allow users
to specify common configure options.
`CMakePresets.json` and `CMakeUserPresets.json` live in the project's
root directory. They both have exactly the same format, and both are
optional (though at least one must be present if `--preset` is
specified). `CMakePresets.json` is meant to specify project-wide build
details, while `CMakeUserPresets.json` is meant for developers to
specify their own local build details.
`CMakePresets.json` is tracked by Git and added into a repository, and
`CMakeUserPresets.json` is not tracked by Git and thus added to the
`.gitignore`.
The patch add …
=> cmake: add presets

CMakeLists.txt, cmake/BuildLua.cmake, cmake/BuildLuaJIT.cmake
The project builds a Lua library that used for building tests using `ExternalProject_Add` in CMake modules. Previously, source repositories with Lua libraries (Lua and LuaJIT) were not updated automatically on rebuilding tests and building tests with updated Lua libraries required rebuild from scratch.
The patch disables `UPDATE_DISCONNECTED` in `ExternalProject_Add` and sets `GIT_REMOTE_UPDATE_STRATEGY` to `REBASE` [1].
After these changes CMake will try to rebase the current branch to the one specified by `LUA_VERSION`. If there are local uncommitted changes, they will be stashed first and popped again after rebasing. If rebasing or popping stashed changes fail, abort the rebase and halt with an error. The strategy could be overriden with
`CMAKE_EP_GIT_REMOTE_UPDATE_STRATEGY`.
1. …
=> cmake: update source repository on rebuild

tests/capi/CMakeLists.txt, tests/capi/luaL_loadbufferx_test.c
Commit 8923c9252cc4 ("tests: update luaL_loadbufferx_test") updated test luaL_loadbufferx_test: test use binary and text mode for PUC Rio Lua and text mode only for LuaJIT. However, test uses a seed corpus that is shared for both Lua implementations, and I suppose crashes like below were happened due to this.
```
SCARINESS: 51 (8-byte-read-heap-use-after-free)
#0 0x5de26e in lj_gc_finalize_cdata /src/testdir/build/luajit-v2.1/source/src/lj_gc.c:591:18
#1 0x56c037 in cpfinalize /src/testdir/build/luajit-v2.1/source/src/lj_state.c:289:3
#2 0x5da933 in lj_vm_cpcall /src/testdir/build/luajit-v2.1/source/src/lj_vm.S:1250
#3 0x56bee4 in lua_close /src/testdir/build/luajit-v2.1/source/src/lj_state.c:316:9
#4 0x569f44 in LLVMFuzzerTestOneInput /src/testdir/tests/luaL_loadbufferx_test.c:43:2
``` …
=> tests/luaL_loadbufferx_test: enable back for LuaJIT

tests/capi/luaL_loadbuffer_proto/luaL_loadbuffer_proto_test.cc
Disable strip of debug information about the function passed to `lua_dump`, see [1]:
> If strip is true, the binary representation may not
> include all debug information about the function, to save space.
This change is likely to increase the code coverage.
1. https://www.lua.org/manual/5.3/manual.html#lua_dump
=> tests: enable debug information in lua_dump

.github/workflows/cflite_batch.yml, .github/workflows/cflite_build.yml, .github/workflows/cflite_cron.yml, .github/workflows/cflite_pr.yml, .github/workflows/check.yaml, .github/workflows/test.yaml
New version fixes a warning in a Github Action web UI:
> Node.js 16 actions are deprecated. Please update the following actions
> to use Node.js 20: actions/checkout@v3. For more information see:
> https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> ci: bump version of actions/checkout

tests/capi/CMakeLists.txt
The patch changes a message that CMake outputs on creating a CTest test, now message highlights that it is a Lua C API test. It is needed to distinquish with Lua API tests.
The patch follows up commit e0216377d750 ("cmake: put C API tests to a separate subdirectory").
=> tests: update message on creating test

.github/workflows/cflite_batch.yml, .github/workflows/cflite_build.yml, .github/workflows/cflite_cron.yml, .github/workflows/cflite_pr.yml
GH Action with enabled options `report-timeouts` and `report-ooms` [1][2] is not released yet. The patch changes a version to `master` to allow using of aforementioned options.
1. https://github.com/google/oss-fuzz/issues/11723
2. https://github.com/google/clusterfuzzlite/pull/138
=> cfl: change a version of gh action

tests/capi/luaL_loadbuffer_proto/serializer.cc
- clamp before cleaning string because cleaning is not cheap (O(n), where max `n` is equal to `kMaxStrLength`)
- call cleaning for identifiers only, there is no sense to cleaning string literals
- replace not allowed symbols in indentifier's names with '_'
This change saves 16 sec on 145k samples (before 401 sec and after 385 sec). It is actually not so much, but it is a 2.5 min per hour.
=> Speedup string serialization

patches/puc-rio-lua.patch
The commit 366c85564874 ("lua.c loads 'readline' dynamically") [1] breaks a build. The proposed patches fixes that.
1. https://github.com/lua/lua/commit/366c85564874d560b3608349f752e9e490f9002d
=> patches: fix PUC Rio Lua build

CMakeLists.txt, libluamut/CMakeLists.txt, libluamut/README.md, libluamut/crossover.c, libluamut/mutate.c, libluamut/tests/CMakeLists.txt, libluamut/tests/crossover_basic_test.c, libluamut/tests/crossover_e2e_test.c, libluamut/tests/crossover_seed_test.c, libluamut/tests/mutator_basic_test.c, libluamut/tests/mutator_e2e_test.c, libluamut/tests/mutator_seed_test.c, libluamut/tests/script_basic.lua, libluamut/tests/script_e2e.lua, libluamut/tests/script_seed.lua, tests/capi/luaL_loadbuffer_proto/luaL_loadbuffer_proto_test.cc
Add a shared library that implements Lua custom mutation and crossover functions.
LibFuzzer allows using custom mutation and crossover functions with `LLVMFuzzerCustomMutator` and `LLVMFuzzerCustomCrossover`.
For using custom mutation function, one need either create a Lua script with `LLVMFuzzerCustomMutator` function and set path to a script to LIBFUZZER_LUA_SCRIPT environment variable. When environment variable `LIBFUZZER_LUA_SCRIPT` is not set, default script name `libfuzzer_lua_script.lua` will be used. The with custom crossover function - one need either create a Lua script with `LLVMFuzzerCustomCrossover` function and set a path to `LIBFUZZER_LUA_SCRIPT` environment variable.
Pay attention that both functions uses its own Lua state internally.
Currently, libluamut is unused and …
=> libluamut: initial version

tests/capi/CMakeLists.txt
The commit 15388716f29d ("tests: disable lua_dump_test").
1. https://github.com/ligurio/lua-c-api-tests/issues/19
=> tests/capi: update blacklists with tests

.github/workflows/test.yaml, CMakeLists.txt, README.md, libluamut/CMakeLists.txt
The patch introduce an option ENABLE_INTERNAL_TESTS, it is disabled by default.
Follows up commit 2ec5436e90f1 ("libluamut: initial version").
=> cmake: introduce an option ENABLE_INTERNAL_TESTS

cmake/BuildLuaJIT.cmake, patches/luajit-dmalloc-asan_instr-v2.1.patch
```
Author: Sergey Bronnikov <estetus@gmail.com>
Date:   Fri Jun 14 15:44:21 2024 +0300
patches: support instrumenting dlmalloc by ASAN
The patch add a patch that implements support of AddressSanitizer
in LuaJIT's dlmalloc. The work has been done by Maksim Tiushev in
Tarantool Lab.
```
=> patches: support instrumenting dlmalloc by ASAN

tests/capi/CMakeLists.txt, tests/capi/ffi_cdef_proto/CMakeLists.txt, tests/capi/ffi_cdef_proto/cdef.proto, tests/capi/ffi_cdef_proto/cdef_print.cc, tests/capi/ffi_cdef_proto/cdef_print.h, tests/capi/ffi_cdef_proto/ffi_cdef_proto_test.cc
LuaJIT has a FFI library which allows calling external C functions and using C data structures from a pure Lua code, see [1].
According to a FFI API documentation [2] the Lua function `ffi.cdef(def)` adds multiple C declarations for types or external symbols (named variables or functions). `def` must be a Lua string. The contents of the string `def` must be a sequence of C declarations, separated by semicolons. The C parser complies to the C99 language standard plus the extensions described in [3].
Note, LuaJIT C parser is not a validating C parser. It expects and accepts correctly formed C declarations. Therefore without grammar-aware fuzzing we will face with a false-positive crashes.
The patch adds a grammar-aware test, where C declarations generated automatically using Protobuf …
=> tests: introduce ffi_cdef_proto_test

.clusterfuzzlite/Dockerfile, .github/workflows/test.yaml, .gitmodules, README.md
A Git submodule was introduced in commit 341ac1ea1619 ("corpus: initial integration"). The main idea was to keep in sync source code of tests and their seed corpus.
However, this approach is not convenient:
- seed corpus updates often and someone need to regularly bump submodule version, otherwise outdated seed corpus is used
- seed corpus takes about 5Gb and git clone of repository with tests takes significant time
=> corpus: remove submodule

tests/capi/lua_load_test.cc
```
[ 66%] Built target lua_mutate
/home/sergeyb/sources/lua-c-api-tests/tests/capi/lua_load_test.cc:62:14: warning: unused variable 'mode' [-Wunused-variable]
62 |         const char *mode = "t";
|                     ^~~~
```
=> tests/capi: fix compiler warning

.github/workflows/test.yaml, README.md
Requires tarantool/tarantool#10911
=> ci: build Tarantool tests

tests/capi/luaL_loadbuffer_proto/luaL_loadbuffer_proto_test.cc
The patch fixes a compiler warning:
```
/home/sergeyb/sources/lua-c-api-tests/tests/capi/luaL_loadbuffer_proto/luaL_loadbuffer_proto_test.cc:371:32: warning: cast from 'void (*)(lua_State
*, void *, size_t *)' (aka 'void (*)(lua_State *, void *, unsigned long *)') to 'luaJIT_profile_callback' (aka 'void (*)(void *, lua_State *, int,
int)') converts to incompatible function type [-Wcast-function-type-mismatch]
371 |         luaJIT_profile_start(L, mode, (luaJIT_profile_callback)profiler_cb, NULL);
|                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
=> test/capi: fix compiler warning in profiler_cb

tests/capi/luaL_loadbuffer_proto/serializer.cc
This patch fixes the Lua inputs in `luaL_loadbuffer_fuzzer` that generate the infinite cycles or recursive function calls, like the following:
```
if counter_0 > 5 then break end
counter_0 = counter_0 + 1
and (0.000000 );
```
The `and` here is generated by the `NameToString()` function, which doesn't check that the name shouldn't be reserved.
This patch adds the corresponding check and separates the counter increment with `;` to avoid any ambiguous syntax.
Follows up the commit 82ec1cc79cf7 ("tests: fix errors "'<name>' expected near 'and'"").
Backported https://github.com/tarantool/tarantool/commit/5836426ccb1e84335d0227a9b8be07e533f5583e
=> tests/capi: fix possible timeout in result chunks

tests/lapi/lib.lua, tests/lapi/math_abs_test.lua, tests/lapi/math_acos_test.lua, tests/lapi/math_asin_test.lua, tests/lapi/math_atan_test.lua, tests/lapi/math_ceil_test.lua, tests/lapi/math_cos_test.lua, tests/lapi/math_deg_test.lua, tests/lapi/math_exp_test.lua, tests/lapi/math_floor_test.lua, tests/lapi/math_fmod_test.lua, tests/lapi/math_log_test.lua, tests/lapi/math_modf_test.lua, tests/lapi/math_pow_test.lua, tests/lapi/math_rad_test.lua, tests/lapi/math_randomseed_test.lua, tests/lapi/math_sin_test.lua, tests/lapi/math_sqrt_test.lua, tests/lapi/math_tan_test.lua, tests/lapi/math_tointeger_test.lua, tests/lapi/math_ult_test.lua
Depends on https://github.com/ligurio/lua-c-api-tests/pull/121.
=>  tests/lapi: add math tests

cmake/BuildLua.cmake, tests/lapi/lib.lua, tests/lapi/string_byte_test.lua, tests/lapi/string_char_test.lua, tests/lapi/string_dump_test.lua, tests/lapi/string_find_test.lua, tests/lapi/string_format_test.lua, tests/lapi/string_gmatch_test.lua, tests/lapi/string_gsub_test.lua, tests/lapi/string_len_test.lua, tests/lapi/string_lower_test.lua, tests/lapi/string_match_test.lua, tests/lapi/string_pack_test.lua, tests/lapi/string_packsize_test.lua, tests/lapi/string_rep_test.lua, tests/lapi/string_reverse_test.lua, tests/lapi/string_sub_test.lua, tests/lapi/string_unpack_test.lua, tests/lapi/string_upper_test.lua
Depends on
- https://github.com/ligurio/lua-c-api-tests/pull/121
- https://github.com/ligurio/luzer/issues/44
=>  tests/lapi: add string tests

tests/capi/luaL_bufflen_test.c
In the latest commits LUAI_MAXSTACK is defined privately [1]:
> LUAI_MAXSTACK is limited to INT_MAX/2, so can use INT_MAX/2 to
> define pseudo-indices (LUA_REGISTRYINDEX) in 'lua.h'. A change
> in the maximum stack size does not need to change the Lua-C ABI.
1. https://github.com/lua/lua/commit/59a1adf194efe43741c2bb2005d93d8320a19d14
=> tests/capi: fix building luaL_bufflen_test

cmake/BuildLuzer.cmake, tests/lapi/coroutine_torture_test.lua
Depends on https://github.com/ligurio/luzer/pull/57
=> tests/lapi: add coroutine test

tests/capi/luaL_loadbuffer_proto/luaL_loadbuffer_proto_test.cc
The patch removes debug hook and testing using bytecode in luaL_loadbuffer_proto_test. Debug hook was added in the commit c772887631f6 ("tests: enable debug hook in luaL_loadbuffer_proto"), the hook slows down execution, breaks JIT compilation in LuaJIT and there were no bugs found with it. Testing with bytecode has been added the commit 0b8c9b8a44d2 ("tests: execute bytecode in luaL_loadbuffer_proto_test"), it slows down running each chunk in two times and there were no bugs found by added function.
=> tests/capi: speedup luaL_loadbuffer_proto_test

cmake/BuildLuzer.cmake, tests/lapi/builtin_pairs_test.lua, tests/lapi/lib.lua, tests/lapi/os_date_test.lua, tests/lapi/os_setlocale_test.lua, tests/lapi/os_time_test.lua, tests/lapi/string_byte_test.lua, tests/lapi/string_rep_test.lua, tests/lapi/table_clear_test.lua, tests/lapi/table_remove_test.lua
**Blocked by** https://github.com/ligurio/luzer/pull/62
=> Fix Lua API tests
